### ISSUE TITLE
Support non-geojson hydrofabrics

### ISSUE THREAD

**Issue by robertbartel** [NOAA-OWP/DMOD#126]
There has been enough discussion about this that it is clearly feature that we will eventually need to support.  The first subtask for this, though, it establishing whether it needs to be in the time table of the current milestone/artifact.  

If it is decided to be part of a later milestone, this will need to be unlinked from the current parent issue and otherwise adjusted to reflect that.

Regardless, this will also need to eventually be broken down into other subtasks.

**Comment by christophertubbs** [comment]
Could this just be handled through a shapefile zip? If so, the laziest (inefficient and shouldn't be long lasting) solution would be to load the shapefile into pandas and transform it into geojson from there.

**Comment by robertbartel** [comment]
Putting this in "Requested" for now, as we need to establish the scope of required support.  Note that this means the "Size" may need to be adjusted.

I.e., just adding another dataset format is pretty easy.  Of course, we would need to integrate the format into GUI map views.  And there is the question of whether the framework natively handles the format.

Alternatively, DMOD could potentially derive GeoJSON hydrofabrics from those of another format.  This would, of course, be more complicated to implement, but it would be a complete (and relatively tighly-contained) solution.

There may also be other minor ancillary things to consider, like the ability to read the hydrofabrics in new formats in order to automatically determine the appropriate dataset domain.

**Comment by robertbartel** [comment]
Marking as closed.  AFAIK, the only non-geojson hydrofabric format that has been discussed to any significant degree has be geopackage, and there is now support for that in DMOD.  Other issues can be opened in the future if more formats come up.
