### ISSUE TITLE
Improve support for newer Docker Compose and environment variable substitution with Swarm

### ISSUE THREAD

**Issue by robertbartel** [NOAA-OWP/DMOD#133]
As documented [here](https://github.com/moby/moby/issues/29133#issuecomment-442912378), the `docker stack` command doesn't support [environmental variable substitution](https://docs.docker.com/compose/environment-variables/#substitute-environment-variables-in-compose-files) in the same way that `docker-compose` does.  To work around this, DMOD has generated temporary config yaml files by preprocessing them using `docker-compose config`.  This outputs the contents of a valid Compose file supplied to it, either as the implied default or explicitly using the `-f` flag, _after_ performing variable substitution.

However, as of Compose versions >= 2.x, [this won't work](https://github.com/docker/compose/issues/8950).  Once adhering to the Compose V2 spec, the `docker-compose config` command omits the `version` element, leading to problems with Swarm interpreting the version of the Compose file specification being used.

It is possible (at least for now) to control whether to "Use Docker Compose V2" in the General section of Docker Desktop settings.  But this may not always be a sufficient workaround, and a better solution could become necessary before a complete fix is supplied on the Docker side.

**Comment by aaraney** [comment]
This will need to be tested, but https://github.com/aaraney/deployx should solve this issue.

**Comment by robertbartel** [comment]
With the merge of #334, this can now be closed.

As a note for the record, it won't hurt to occassionally check in on this Moby issue on [the lack of direct .env file support by `docker stack`](https://github.com/moby/moby/issues/29133), and this Docker CLI issue on [`docker stack` properly adopting the compose spec](https://github.com/docker/cli/issues/2527).
