### ISSUE TITLE
DMOD gh-page documentation

### ISSUE THREAD

**Issue by aaraney** [NOAA-OWP/DMOD#15]
It would be nice to have a github io page for this project. We could use sphinx and autodocs to automatically build the api documentation and mirror the readme on the front page for starters. Is this a feature that desired? If so, have guidelines been set for gh-pages? More or less just staring a conversation here.

Personally, using sphinx with the readthedocs theme on a gh-pages hosted site is what I would propose.

**Comment by hellkite500** [comment]
I think we should do this, but just haven't yet.  We should be able to deploy to gh-pages pretty simply, and add an action to build the doc pages on push.

**Comment by aaraney** [comment]
@hellkite500 Can you label this as enhancement and help wanted? I don't have those permission in this repo.

Additionally, as for gh-pages, which do you prefer? sphinx or mkdocs? Personally I think mkdocs is way simpler to use and get started with, it is just a shame that it doesn't offer an automated docstring documentation generator out of the box.

Another more concrete question, if the choice is sphinx, do you prefer markdown or restructured text?

**Comment by hellkite500** [comment]
Sorry this got lost in the queue of GH things.  I'm not up to speed on the tradeoffs of these systems (sphinx vs mkdocs, markdown vs restructured text) so I don't know how to answer that just yet.

**Comment by aaraney** [comment]
No worries, I am about to do this for [`evaluation_tools`](https://github.com/NOAA-OWP/evaluation_tools) so if you are satisfied with how it looks there, feel free to poach that work and implement it here.
