### ISSUE TITLE
ResourceManager round robin allocation paradigm docstring out of date

### ISSUE THREAD

**Issue by aaraney** [NOAA-OWP/DMOD#221]
I believe 6c674e186c4005cd042d90c298f8054a6a7e826c makes the [`ResourceManager.allocate_round_robin`'s docstring](https://github.com/NOAA-OWP/DMOD/blob/267428bd903dd0f58bfbdba7620f77af03b30cff/python/lib/scheduler/dmod/scheduler/resources/resource_manager.py#L234) out of date. The round robin method nows covers this case.

https://github.com/NOAA-OWP/DMOD/blob/267428bd903dd0f58bfbdba7620f77af03b30cff/python/lib/scheduler/dmod/scheduler/resources/resource_manager.py#L239-L243

**Comment by robertbartel** [comment]
Closed by #581.
