### ISSUE TITLE
Update package script fails if wheel package not installed

### ISSUE THREAD

**Issue by aaraney** [NOAA-OWP/DMOD#247]
Installing packages using `scripts/update_package.sh` fails if `wheel` package is not installed in environment.

## Current behavior

1. clone repo
2. create virtual environment and update pip

    ```shell
    python -m venv venv
    source ./venv/bin/activate
    python -m pip install -U pip
    ```

3. run `scripts/update_package.sh`
4. fails because `wheel` not installed

## Expected behavior

3. `wheel` is installed, if required and `scripts/update_package.sh` does not fail

## Proposed solution

In short, add `pyproject.toml` configuration file to all subpackages and specify `wheel` as a build time dependency. 

[PEP 518](https://peps.python.org/pep-0518/) -- "Specifying Minimum Build System Requirements for Python Projects", introduced the ability to specify build requirements in a new `pyproject.toml` configuration file. This file is respected and used by package installers (i.e. `pip`) to verify that build time dependencies are satisfied and installed if required.

Assuming this solution is accepted, before introducing `pyproject.toml`s, it is prerequisite that we determine the minimum required `wheel` and `setuptools` versions.

**Comment by robertbartel** [comment]
I don't see this as a bug, per se.  The issue is that **step 2** doesn't include the command to install things from _requirements.txt_.  Those project development dependencies are documented in _doc/DEPENDENCIES.md_, and those details are referenced and linked within the main _README.md_.  There are also helper options for that in _scripts/update_package.sh_.

All that said, this certainly demonstrates that things aren't already handled perfectly and that we should look at improvements.

> In short, add pyproject.toml configuration file to all subpackages and specify wheel as a build time dependency.

I am fine with going this direction, but if this isn't a bug or otherwise essential, we will need to prioritize it lower.

**Comment by aaraney** [comment]
> I don't see this as a bug, per se. The issue is that **step 2** doesn't include the command to install things from _requirements.txt_. Those project development dependencies are documented in _doc/DEPENDENCIES.md_, and those details are referenced and linked within the main _README.md_. There are also helper options for that in _scripts/update_package.sh_.

Austin, just read the manual... haha. That's fair. My only rebuttal, if you would even call it that :), is that I think you should be able to install a package's dependencies through `setup.py` or an equivalent package metadata file. That implies that for any package, all required dependencies for that package are all listed in its `setup.py`. This is not the case at the moment.

**Comment by robertbartel** [comment]
I'm bumping the project priority of this to _High_, and will move into _Accepted_.  Given our hopes for accelerated involvement of others in the community in the near term, we want to get rid of roadblocks like this.
