### ISSUE TITLE
Investigate need to replace setup.py with newer configuration files

### ISSUE THREAD

**Issue by aaraney** [NOAA-OWP/DMOD#248]
In recent years, the python community has moved away from specifying package metadata in `setuptools`'s `setup.py` in favor of a new `setuptools` ini-like file, [`setup.cfg`](https://setuptools.pypa.io/en/latest/userguide/declarative_config.html) (added in `setuptools==30.3.0`). `setup.cfg` is a declarative ini-like file for declaring package metadata that normally is supplied in `setup.py`'s `setup()` function. The main motivations for the switch are security concerns present during the execution of arbitrary python code in `setup.py` during build and installation. This issue is to discuss if and when we should move to `setup.cfg` and evaluate the necessary changes to build scripts and documentation to make a pending transition seamless.

Motivation for opening this issue is related to #247. Specifically, legacy treatment of `setup.py install` by `pip`. 

Below is a warning thrown by `pip` when installing any `dmod` subpackage in a python environment that does not have the `wheel` package installed:

```shell
DEPRECATION: dmod-core is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
```

If `wheel` is installed or specified as a build time dependency in `pyproject.toml` this currently will not be raised. As such, this may never be a big deal, neglecting potential security concerns, assuming `pip` will always have legacy support for `setup.py`. However, it is clear that `setup.cfg` is the now preferred way of specifying package metadata and is likely a wise longterm decision. 

Below is an example `setup.cfg` sourced from [`setuptools` documentation](https://setuptools.pypa.io/en/latest/userguide/declarative_config.html):

```ini
[metadata]
name = my_package
version = attr: my_package.VERSION
author = Josiah Carberry
author_email = josiah_carberry@brown.edu
description = My package description
long_description = file: README.rst, CHANGELOG.rst, LICENSE.rst
keywords = one, two
license = BSD-3-Clause
classifiers =
    Framework :: Django
    Programming Language :: Python :: 3

[options]
zip_safe = False
include_package_data = True
packages = find:
python_requires = >=3.7
install_requires =
    requests
    importlib-metadata; python_version<"3.8"

[options.package_data]
* = *.txt, *.rst
hello = *.msg

[options.entry_points]
console_scripts =
    executable-name = my_package.module:function

[options.extras_require]
pdf = ReportLab>=1.2; RXP
rest = docutils>=0.3; pack ==1.1, ==1.3

[options.packages.find]
exclude =
    examples*
    tools*
    docs*
    my_package.tests*
```

**Comment by robertbartel** [comment]
> As such, this may never be a big deal, neglecting potential security concerns, assuming pip will always have legacy support for setup.py. However, it is clear that setup.cfg is the now preferred way of specifying package metadata and is likely a wise longterm decision.

I think this says everything:
- security concerns (or at least the appearance of such, which can be its own problem)
- a good chance this will break in the not-too-distance future
- discouraging community usage

So, we should address it.

But we'll have to be thoughtful about how we prioritize it.  For the moment, I would put it very low on our list, especially considering the scope of chances I'd expect (on first glance).  

I'm interested in hearing any arguments for bumping it higher, though.
