### ISSUE TITLE
Add t-route config data format and incorporate use of necessary datasets for routing

### ISSUE THREAD

**Issue by robertbartel** [NOAA-OWP/DMOD#252]
This will include (at minimum):

- [ ] Creating a new _DataFormat_
- [ ] Updating the realization config _DataFormat_ or otherwise providing an indicator within DMOD for when a Nextgen job will require routing
- [ ] Updating workflow execution to create _DataRequirement_ instance, etc. to handling running a job that includes routing
- [ ] Ensure the configured `geo_file_path` (e.g., _flowpath_parameters_mod.json_) and `flowpath_edge_list` (_flowpath_edge_list.json_) files are either part of dataset directly or domains ensure they are made available
- [ ] Collaborate with t-route team to integrate `pydantic` data models that capture the contents of a t-route config (https://github.com/NOAA-OWP/t-route/issues/618)
- [x] Implement `pydantic` data models that capture the contents of a t-route config.

**Comment by aaraney** [comment]
Im curious if we will be able to leverage the work from #280 to fulfill or partially fulfill this?

**Comment by aaraney** [comment]
Moving this to blocked until we hear back from the t-route team.
