### ISSUE TITLE
Transfer Evaluation Service pages to the GUI

### ISSUE THREAD

**Issue by christophertubbs** [NOAA-OWP/DMOD#259]
The evaluation service has multiple pages that need to be transferred to the GUI:

- evaluation_listing
- ready_evaluation_async

Any gaps between the two (such as the active map functionality and a way to connect websockets) need to be implemented as well.

**Comment by robertbartel** [comment]
Blocked by #260.

**Comment by robertbartel** [comment]
I believe this corresponds directly to #305.

**Comment by robertbartel** [comment]
@christophertubbs, I am going to go ahead and close this with the merging of #305.
