### ISSUE TITLE
Decouple model image handling from DMOD required services

### ISSUE THREAD

**Issue by hellkite500** [NOAA-OWP/DMOD#28]
As new models/workflow are envisioned for use within DMOD, a clear seperation of the DMOD services, such as `request-service`, and the model images such as `nwm` should be established.

## Current behavior

The `main` stack is built and pushed including the model images from the same configuration files (`docker/main/docker-build.yml` and `docker/main/docker-deploy.yml`

## Expected behavior

The main stack should build and deploy only required DMOD services, irregardless of the available model images.  A separate directory, like `docker/main/models` or maybe even `docker/models` would hold the main build definitions (since we aren't decploying these as services, no deploy file is needed) and the upstack/control_stack utilities can be refactored to build and push model images (or verify they are available).

## Discussion Points
The only place this becomes potentially problematic is connecting the `image_and_domain.yml`that is used by the scheduler/launcher.

**Comment by aaraney** [comment]
Yeah, I generally don't disagree. The purpose of the `docker-build.yml` is to support building the entire dmod feature set. I would classify what you are proposing here as a deployment / build specific details. There is nothing stopping someone from commenting out the models that are built in `docker-build.yml`. To your point, it would be _nice_ if there was more separation, but I don't think, at least at this point, that level of separation adds anything more than another level of indirection.
