### ISSUE TITLE
Migrate all GUI code to React/Next.js

### ISSUE THREAD

**Issue by robertbartel** [NOAA-OWP/DMOD#286]
In an effort to improve code quality, easy development, and give a consistent look to everything, investigate and then move GUI code from current implementations - most of which is Django-based - to an implementation using React and Next.js.  This was the toolset used to implement the Calibration workflow execution menus as demonstrated in the OWP Townhall presentation at AGU Fall Meeting 2022.

- [x] #287
- [x] #293
- [x] #295
- [x] #294
- [ ] Refactor or remove legacy components

**Comment by aaraney** [comment]
Thanks for finding this library, @christophertubbs! Reading through their readme I'm not sure if this will help as much as it will hurt in the long run (as always, please share your perspective).

> You are starting a new project and you want to use Django as back-end and Next.js as front-end. Django only serves API requests. All front-end code lives in Next.js and you don't write any Django template.
>
> In this scenario you don't need this package (although you can use it). You simply start both Django and Next.js servers and point your public webserver to Next.js.

At this point, at least in my perspective, the GUI stack and views are small enough that porting them to next.js and react should be straightforward and minimally painful. I guess what I'm trying to say is I don't think we have enough Django views at this point to require using this kind of tooling. However, we should be able to use the existing Django channels and rest handler's to drive the ported functionality. I'm definitely not advocating that we move our gateway (backend for front end) functionality into next.js. Thoughts?

**Comment by christophertubbs** [comment]
I think it all depends on how we get functionality driving variables into the pages. A good bit of that functionality has been thankfully separated out into smaller blocks. `map.html`, for example, uses these `datapane` objects. If nextjs/react/etc doesn't already have something like that, there's already separate JS code incorporated into the page to drive its behavior (popping in and out, adding new items to the list, etc). We'll just need a way to make sure stuff like `select` values are fed in, whether the values come from a page load event or from the nextjs service, a computer gremlin, or whatever.

**Comment by aaraney** [comment]
Ah, so I am taking this to mean basically how do you pass and modify state between different components that are on the DOM? That's a great question! So, for example, when you click a _thing_ on the map, it adds a _thing_ description to a table on the left. Am I following you?

If I am, react has a lot of ways to handle and manage state. For the use case you mentioned in particular, react has the concept of a [context](https://beta.reactjs.org/reference/react/createContext) and a [`useContext` hook](https://beta.reactjs.org/reference/react/useContext) components can access and mutate state in that context. I think its safe to think of contexts as scoped containers (i.e. map, vector) that descendent components of that scope can, by using the hook, access and mutate the state in that context. Crucially, react will re-render components that read from the `useContext` hook _when_ the context changes. So, it feels a lot like an observer pattern, you write to the context and any context listeners are given the new data and re-rendered.

So, in your example, you might create a map feature context that is a parent of both the map and pop out table thingy. Both the map and table thingy use the `useContext` hook to mutate and access some state they are interested in and when either of them write to the context, they are both re-rendered (this is not exactly right, there are ways to avoid re-rendering, in particular children of the map and table thingy component for performance reasons but that is beyond the scope of what we are talking about).

**Comment by christophertubbs** [comment]
It sounds like that's what I'm looking for. At this point, would the code looking for context be running client side and communicating with a Django view or websocket consumer?

Here's another example I've got going on in a template that **only** handles the addition of CodeMirror editors (there's one page that has three for sending and viewing JSON). This template only operates when embedded _within_ another template.

```html
<script>
    {% block codeViewAddition %}
    {% if code_views %}
    {% autoescape off %}
    codeViews.push.apply(codeViews, {{ code_views }});
    {% endautoescape %}
    {% endif %}
    {% endblock codeViewAddition %}
</script>
```

`codeViews` is an `object` storing javascript `object`s that tell the client where to put editors on page load. If the view doesn't define the `code_views` object in the context sent to the renderer, no harm, no foul. Nothing is added on page load, though more may be added later.

The server-side rendering code then looks like:

```python
        page_identifier = common.generate_identifier()
        page_key = common.generate_key()

        editors = CodeViews()

        editors.add(
            name="editor",
            tab="edit-div",
            container="editor-content",
            textarea="#instructions",
            config={
                "mode": "javascript",
                "json": True,
                "allowDropFileTypes": ['application/json'],
            }
        )

        editors.add(
            name="messages",
            tab="message-div",
            container="message-area",
            textarea="#messages",
            config={
                "mode": "javascript",
                "json": True,
                "readOnly": True,
                "gutters": ["CodeMirror-foldgutter"]
            }
        )

        editors.add(
            name="digest",
            tab="digest-div",
            container="digest-content",
            textarea="#digest-text",
            config={
                "mode": "javascript",
                "json": True,
                "readOnly": True,
                "gutters": ["CodeMirror-foldgutter"]
            }
        )

        notifiers: typing.List[Notifier] = list()

        notifiers.append(
            Notifier("notifier-popup", "Notifications", "/ws/notifications")
        )

        context = {
            "evaluation_template": self.get_evaluation_template(),
            "launch_url": f'/{forwarding.get_forward_socket_route("EvaluationService")}',
            "metrics_url": f'/{forwarding.get_forward_rest_route("EvaluationService", "metrics")}',
            "geometry_url": f'/{forwarding.get_forward_rest_route("EvaluationService", "geometry")}',
            "generated_evaluation_id": self._generate_evaluation_id(request),
            "evaluation_id_pattern": EVALUATION_ID_PATTERN,
            "production": not application_values.in_debug_mode(),
            "page_identifier": page_identifier,
            "page_key": page_key,
            "code_views": editors.to_json(),
            "notifiers": notifiers
        }

        payload = Payload(request, **context)

        page_response = render(request, template_name=self.template, context=payload.to_dict())
```

That payload dictionary is a pure dictionary sent to Django's rendering engine where each one of those variables is a variable that may be used in the template, so I can drive behavior in the renderer via blocks like `{% if production %}<span>This example won't show up in a dev build</span>{% endif %}`. Some of this can drive fundamental behavior. That payload contains a mapping for what URLs to communicate with, for example.
