### ISSUE TITLE
Investigate/confirm feasibility with discussion and simple test comparison views implemented both in current and proposed toolsets

### ISSUE THREAD

**Issue by robertbartel** [NOAA-OWP/DMOD#287]

**Comment by robertbartel** [comment]
I thought the plan was to build and compare implementations of the same user-facing functionality in both the current toolset and in React/Next.js, and see where that got us.  We can pivot from that if appropriate, though.

**Comment by aaraney** [comment]
I thought this was mainly referring to reproducing the websocket observer thing @christophertubbs showed us two weeks ago. The debug view where you could hit a rest endpoint from one tab and it would update and populate more information in a different connection in a different tab. What you said, @robertbartel, sounds broader.

**Comment by christophertubbs** [comment]
I'd stick with just worry about a single view for now. The intel that grants us will help us know where to steer.  We can look at converting others after the initial prototype is built.
