### ISSUE TITLE
Implement conversions from geopackage hydrofabric to geojson

### ISSUE THREAD

**Issue by robertbartel** [NOAA-OWP/DMOD#298]
Implement logic to convert from Geopackage hydrofabric to GeoJSON hydrofabric.  The most important feature for this is the ability to go from a Geopackage to GeoJSON files, mainly for purposes of supporting the ngen framework.

Note that it will likely be necessary to do some reprojection as an intermediate step in this process.

This requires the prerequisite #296 to be approved and merged before it can be completed.

**Comment by aaraney** [comment]
@robertbartel, are you thinking this would live in the `hydrofabric` package?

**Comment by aaraney** [comment]
Is this still required now that https://github.com/NOAA-OWP/ngen/pull/522 has been merged?
