### ISSUE TITLE
Update to new hypy dependency and fix catchment class type hinting

### ISSUE THREAD

**Issue by robertbartel** [NOAA-OWP/DMOD#311]
See [this comment](https://github.com/NOAA-OWP/DMOD/pull/296#discussion_r1142553593).  The specialized catchment and nexus classes added within that PR will need type hints corrected for several functions to properly reflect variable length.  

However, this cannot be done until an updated version of https://github.com/NOAA-OWP/hypy is available that addresses https://github.com/NOAA-OWP/hypy/issues/23.

This will relate to #310.

**Comment by robertbartel** [comment]
Waiting on the review of PR https://github.com/NOAA-OWP/hypy/issues/24 to be completed, and then this can be unblocked.

**Comment by aaraney** [comment]
https://github.com/NOAA-OWP/hypy/pull/24 has been reviewed and merged.

**Comment by robertbartel** [comment]
I'm bumping the priority of this:  with the update to hypy, now DMOD class signatures conflict with the superclasses, so this needs to be fixed.
