### ISSUE TITLE
Address ngen Docker image build issue with Python tables and blosc2 packages

### ISSUE THREAD

**Issue by robertbartel** [NOAA-OWP/DMOD#312]
The _ngen_ Docker image is failing to build due to a problem with the _tables_ Python dependency.  In the `rocky-ngen-deps` build stage, there are these two lines (probably 349).  The second triggers the error, but the first ends up being directly related.

``` Dockerfile
    && pip3 install numpy pandas pyyaml bmipy Cython blosc2 netCDF4 wheel packaging \
    && HDF5_DIR=/usr pip3 install --install-option="\'--hdf5 \${HDF5_DIR}\'" --install-option="\'--jobs=$(nproc) \'"  --no-build-isolation tables \
```

The error (shown below) complains about _skbuild_, but the root of the problem is that _tables_ requires a specific version of _blosc2_, which _at present_ is different than the version of _blosc2_ installed by the previous command.  This then causes dependency issues, and eventually the _tables_ install fails.

This can be fixed by specifying `blosc2==2.0.0` in the first command, but this is a brittle solution.  One way or another, this needs to be fixed, but a more robust solution would be preferable if one is feasible.

The error looks like this:

<img width="1170" alt="Screenshot 2023-03-06 at 14 17 42" src="https://user-images.githubusercontent.com/37884615/226932939-52c19ae2-83ac-4787-906b-768bead61999.png">

**Comment by hellkite500** [comment]
I had success cloning and doing a build/install from the source tree:
```
    # Install required python dependency packages with Pip \
    # Except blosc2, since packaged wheels on pypi seem to have some issues, build it ourselves
    && git clone https://github.com/Blosc/python-blosc2/ \
    && cd python-blosc2 \
    && git submodule update --init --recursive \
    # TODO can checkout a particular tag -- as is you end up wtih a dev version, but it seems to work
    && python3 -m pip install -r requirements-build.txt \
    && pip3 install . \
```

Also, it looks like the `--install-option` flag is deprecated on newer versions of pip/setuptools.  I was able to remove those options and leave the HDF5 env and it seemed to work alright.

**Comment by aaraney** [comment]
It looks like [`--install-option`](https://pip.pypa.io/en/stable/news/#deprecations-and-removals) was removed in `pip 23.1`.
