### ISSUE TITLE
Intended behavior of is_integer and is_float

### ISSUE THREAD

**Issue by aaraney** [NOAA-OWP/DMOD#330]
While working on #314, it was not clear to me the intended behavior of `is_integer` and `is_float`.

https://github.com/NOAA-OWP/DMOD/blob/7cab36fe792ccfc8d9f679ec71bc432fed568485/python/lib/core/dmod/core/common/helper_functions.py#L29-L54

My inclination is that `is_integer(42)` and `is_float(42.0)` should both return `True` but both return `False`. @christophertubbs, is this the intended behavior?

**Comment by aaraney** [comment]
My best guess is that these functions could be re-written as:

```python
def is_integer(value: Any) -> bool:
  return isinstance(value, (int, np.integer))

def is_float(value: Any) -> bool:
  return isinstance(value, (float, np.floating))
```

However since `dmod.core` does not depend on `numpy` they can't be written that way. My guess is that why they are written how they are now. That leads me to think they should live in a module that depends on `numpy`. Thoughts @christophertubbs?

**Comment by christophertubbs** [comment]
Found the issue - `value` at the end of each function is a `type`, so it'll _never_ be an instance of `float` or `int`. Those will need to be rewritten as something like:

```python
def is_integer(value) -> bool:
    value_type = value if type(value) == type else type(value)
  
    mro = get_mro_names(value_type) 
  
    module_name = value_type.__module__ if hasattr(value_type, "__module__") else '' 
  
    if module_name.startswith("numpy"): 
        return "integer" in mro
     
    loaded_integer_types = [int] + int.__subclasses__()
  
    return value in loaded_integer_types if type(value) == type else  isinstance(value, int)
```

**Comment by aaraney** [comment]
> those returning false is _definitely_ wrong. The idea was that this would be usable in any library, whether it used numpy or not and requiring specialized logic if so because the mro for numpy types can be all types of funky.

Yeah, my only reservation is that to properly test these functions we would need to depend on `numpy` as a dev dep and that _feels_ wrong. Like we are solving a problem that we don't have in this context. Do you think that is fair? Or am I being overly harsh?

**Comment by aaraney** [comment]
> Found the issue - `value` at the end of each function is a `type`, so it'll _never_ be an instance of `float` or `int`. Those will need to be rewritten as something like:
> 
> ```python
> def is_integer(value) -> bool:
>     value_type = value if type(value) == type else type(value)
>   
>     mro = get_mro_names(value_type) 
>   
>     module_name = value_type.__module__ if hasattr(value_type, "__module__") else '' 
>   
>     if module_name.startswith("numpy"): 
>         return "integer" in mro
>      
>     loaded_integer_types = [int] + int.__subclasses__()
>   
>     return value in loaded_integer_types if type(value) == type else  isinstance(value, int)
> ```

Equivalently, we could just try to import `numpy` and catch the ModuleNotFoundError if we can't. So something like:

```python
def is_integer(value: Any) -> bool:
  try:
    import numpy as np
    types_to_check = (int, np.integer)
  except ModuleNotFoundError:
    types_to_check = (int,)

  return isinstance(value, types_to_check)


```
