### ISSUE TITLE
Improve useage of Redis, Redis Streams, and other Redis components in inter-service communication

### ISSUE THREAD

**Issue by robertbartel** [NOAA-OWP/DMOD#336]

**Comment by robertbartel** [comment]
@christophertubbs I'm opening this to track this work.  Feel free to split off subtasks as needed for more granular tracking.  If you do, we should probably also change this issue to an _Epic_.

**Comment by christophertubbs** [comment]
The EvaluationService makes heavy use of redis pubsub and the evaluation logic itself may benefit from work distribution like that. Are there any other places where redis streams should be inserted?

**Comment by aaraney** [comment]
Not to get too far ahead of myself while also trying to lay down a little context, I dont think we will _think_ about each service _using_ the broker in the same way, meaning some services we may _think_ of as _passive_ consumers / produces and others as _active_ despite similar semantics. The difference between an active and passive consumer comes down to if the consumer receives "commands" or "events" respectively. An example of what im calling a _passive_ consumer could be the monitoring service. The monitoring service may not be send a "command" like, `{"command": "LISTEN_FOR_JOB", "payload": { "id": "908c6bdb-50d3-48e1-99f2-00db82c0827e" }}` but instead just listens on one or more streams and acts on the information it receives. In contrast, an example of an _active_ consumer could be the data service where some other actor send a command, `CHECK_DATA`, an the data service determines if data exists to satisfy the request and publish an event with the outcome of the check.
