### ISSUE TITLE
Distill the evaluation request messages

### ISSUE THREAD

**Issue by christophertubbs** [NOAA-OWP/DMOD#339]
The pydantic refactoring process led to the evaluation request messages being fairly redundant. Each message generally follows:

```python
class EvaluationRequest(Message):
    """
    A request to be forwarded to the evaluation service
    """

    event_type: typing.ClassVar[MessageEventType] = MessageEventType.EVALUATION_REQUEST
    """ :class:`MessageEventType`: the event type for this message implementation """

    action: str
    parameters: typing.Dict[str, typing.Any] = Field(
        description="Parameters for the action",
        alias="action_parameters"
    )
```

Since the evaluation service has internal routing based on that `action` field, having multiples of this type of class is unnecessary. As a result, they should all be distilled into a single class, like the one above.

The offending classes may be found in python/lib/communication/dmod/communication/evaluation_request.py

**Comment by robertbartel** [comment]
Blocked until #331 is fully merged

**Comment by christophertubbs** [comment]
This might be OBE. A lot of the messaging types have been overhauled with some of the websocket to REST conversions.
