### ISSUE TITLE
Address issues with integration test failures

### ISSUE THREAD

**Issue by robertbartel** [NOAA-OWP/DMOD#352]
There are several failing integration tests in multiple packages.  Note that because they are _integration_ tests, they deliberately aren't run within our Github Actions automation (they require services and other dependencies to be setup, which we cannot do in the Github Action runners).  Still, these items need to be fixed.

``` console
vision:dmod rbartel$ ./scripts/run_tests.sh -srv -it
Executing integration tests on supported packages ...

python/lib/access: FAILED (errors=9) (Ran 37 tests in 46.058s)
python/lib/client: OK (Ran 0 tests in 0.000s)
python/lib/communication: OK (Ran 2 tests in 6.080s)
python/lib/core: OK (Ran 0 tests in 0.000s)
python/lib/evaluations: OK (Ran 0 tests in 0.000s)
python/lib/externalrequests: FAILED (errors=5) (Ran 13 tests in 18.051s)
python/lib/hydrofabric: OK (Ran 0 tests in 0.000s)
python/lib/metrics: OK (Ran 0 tests in 0.000s)
python/lib/modeldata:  (Ran 20 tests in 435.073s)
python/lib/monitor: OK (Ran 0 tests in 0.000s)
python/lib/redis: OK (Ran 0 tests in 0.000s)
python/lib/scheduler:  (Ran 60 tests in 23.656s)
python/services/dataservice: OK (Ran 0 tests in 0.000s)
python/services/monitorservice: OK (Ran 0 tests in 0.000s)
python/services/requestservice: OK (Ran 0 tests in 0.000s)
python/services/schedulerservice: OK (Ran 0 tests in 0.000s)

vision:dmod rbartel$
```

As a reminder, the `scripts/test_package.sh` script has options for running integration tests for an individual package, as well as just running the integrated environment setup (and later teardown) so that tests can be run manually and/or individually (e.g., through an IDE for easier debugging).

**Comment by aaraney** [comment]
I _think_ #358 will fix the `python/lib/access` failures.

**Comment by aaraney** [comment]
Verifying my above statement and investigating the `python/lib/externalrequests` failures.

**Comment by aaraney** [comment]
Verified that #358 fixes the `python/lib/access` failures.

**Comment by aaraney** [comment]
Found the issue affecting `python/lib/externalrequests`. #359 resolves the issue.
