### ISSUE TITLE
Add tests to verify behavior of is_env_workaround in PartialRealizationConfig

### ISSUE THREAD

**Issue by robertbartel** [NOAA-OWP/DMOD#355]
See [this comment](https://github.com/NOAA-OWP/DMOD/pull/316#discussion_r1223486635) from a previous PR.  

Essentially, the `is_env_workaround` is type-hinted as a `bool`, but initially set (at the class level) to `None`.  The idea is that this was intentional, and that a validator is in place to make sure instances always initialize the field to `True` or `False`.

However, we should verify that the validator does provide this guarantee as implement (and if not, make some changes).  The best way to do that is to ensure our unit test coverage is complete for the related scenarios.

**Comment by aaraney** [comment]
@robertbartel, ill have a look at this now and open a PR.
