### ISSUE TITLE
Add TypeScript build documentation

### ISSUE THREAD

**Issue by aaraney** [NOAA-OWP/DMOD#369]
Add docs for how to transpile the typescript libraries to js.

**Comment by christophertubbs** [comment]
Instructions on configuring `--watch` or showing how to do similar stuff using pycharm watchers or vscode tasks would be helpful too. Don't need to remember how to transpile if it just happens automagically once configured.

**Comment by aaraney** [comment]
What we will likely end up doing is have a central `package.json` (think `setup.py` / `setup.cfg` for python) that each `ts` library adds to or modifies. Having looked at several large `typescript` only projects, ive seen this in almost ever one of them.
