### ISSUE TITLE
Incorrect destination variables in dataservice cli 

### ISSUE THREAD

**Issue by aaraney** [NOAA-OWP/DMOD#374]
https://github.com/NOAA-OWP/DMOD/blob/12ccd5ea4ccffc51615c621657b127b509f54fb5/python/services/requestservice/dmod/requestservice/__main__.py#L70-L82

The destination variables should instead be:

`evaluation_service_host`
`evaluation_service_port`
`evaluation_service_ssl_dir`

**Comment by robertbartel** [comment]
Fixed by #433.
