### ISSUE TITLE
Failing tests for dmod.evaluations package

### ISSUE THREAD

**Issue by robertbartel** [NOAA-OWP/DMOD#396]
Several unit tests have begun to fail in _dmod.evaluations_.  This became apparent with the failure of checks in PR #394, although I am able to replicate the test failures locally using the `dev` branch. 

That said, I'm not quite sure what introduced this; checks and tests seem to have passed in the last closed PR, #385, and even in some other recent-but-not closed PRs, like #391.

**Comment by robertbartel** [comment]
@christophertubbs, I'm initially assigning this to you, since you are most familiar with the package.  If you don't think you'll have time to get to this quickly, though, let me know.  I can pick it up if needed, and I don't want the failing checks to linger too long.

**Comment by robertbartel** [comment]
Actually @christophertubbs, I've just noticed that the subsequent PR #395 didn't fail checks.  I'm going to do some more investigating myself, but feel free to pick this up if you have time. In particular, I'm curious if you can replicate failing tests locally on `dev` like I did.

**Comment by christophertubbs** [comment]
What errors arose? I can't find a record of failing tests (probably just because I've never looked before).

**Comment by robertbartel** [comment]
@christophertubbs, [here are the failed tests](https://github.com/NOAA-OWP/DMOD/actions/runs/5579729188/jobs/10217091914?pr=394#step:10:248) within the check of #394.

**Comment by robertbartel** [comment]
FWIW, I re-ran `scripts/update_package.sh`, but this time added `-d` to also update all the project dependencies (i.e., stuff in _requirements.txt_).  After that, the evaluation tests are passing for me locally.

**Comment by christophertubbs** [comment]
Mark me confused - I was just looking at the environment initialization text and it downloaded pandas 2.0.whatever, then pandas 1.5.whatever, then decided to build and install the wheel for 1.1.5? I'd venture to guess that an old version _would_ throw a wrench in there.

Would updating the root `requirements.txt` to read something like `pandas~=1.0` instead of just `pandas` do it? 2+ may be a little too recent and have breaking changes, but I imagine we'd want to keep up with the latest reasonable pandas version.

What's controlling that caching? I know it's the `_version.py` file for 90% of the subprojects, but what is it at the root?

**Comment by christophertubbs** [comment]
`Timestamp.dayofyear` is just an alias for `Timestamp.day_of_year`, at this point, so nuking some underscores could do the trick.

**Comment by robertbartel** [comment]
I've discovered that updating dependencies will cause the problem to toggle off if done in the `dev` branch, and back on if done in the branch for #394.  Here are the differences in pip packages:

``` diff
--- pip_packages.dev-branch	2023-07-18 13:54:27
+++ pip_packages.pr394-branch	2023-07-18 13:57:08
@@ -36,10 +36,10 @@
 djangorestframework       3.14.0
 dmod-access               0.2.1
 dmod-client               0.3.0
-dmod-communication        0.13.0
-dmod-core                 0.9.0
+dmod-communication        0.14.0
+dmod-core                 0.10.0
 dmod-datarequestservice   0.4.1
-dmod-dataservice          0.7.0
+dmod-dataservice          0.8.0
 dmod-evaluations          0.3.0
 dmod-evaluationservice    0.6.1
 dmod-externalrequests     0.4.1
@@ -98,7 +98,7 @@
 numexpr                   2.8.4
 numpy                     1.25.1
 packaging                 23.1
-pandas                    2.0.3
+pandas                    1.1.5
 Pillow                    10.0.0
 Pint                      0.22
 pip                       23.2
@@ -157,7 +157,7 @@
 Werkzeug                  2.3.6
 wheel                     0.40.0
 wrapt                     1.15.0
-xarray                    2023.7.0
+xarray                    2022.3.0
 yarl                      1.8.2
 zipp                      3.15.0
 zope.interface            6.0
```

I would assume the problem is the revert in version of Pandas introduced by #394 (which I have set to _Blocked_ status at the moment).  That issue brought in _ngen-cal_ as a project dependency, in addition to _ngen-config_, which must have caused the Pandas change transitively somehow.

**Comment by robertbartel** [comment]
> `Timestamp.dayofyear` is just an alias for `Timestamp.day_of_year`, at this point, so nuking some underscores could do the trick.

@christophertubbs, I'm alright with that as a fix, but the core problem is that the _pandas_ dependency specification is too unspecific for _dmod.evaluations_.  I'd prefer that be addressed if we can.  

That said, I'm guessing introducing a dependency on `>=2.0.0` will cause problems for #394, so we may need to do what you suggest **and** add a version specifier.  @aaraney, any idea immediately why bringing in _ngen-cal_ would require older _pandas_?

**Comment by robertbartel** [comment]
> Would updating the root _requirements.txt_ to read something like `pandas~=1.0` instead of just `pandas` do it? 2+ may be a little too recent and have breaking changes, but I imagine we'd want to keep up with the latest reasonable pandas version.

The short answer seems to be "no."  I tried that quickly in the PR branch, but still get the 4 test errors.  Version `1.1.5` ends up getting installed still.

**Comment by aaraney** [comment]
> @aaraney, any idea immediately why bringing in _ngen-cal_ would require older _pandas_?

Not off the top of head. @hellkite500?

**Comment by aaraney** [comment]
I opened an issue in the `ngen-cal` repo so we can track this. I agree, @hellkite500, we need to verify if we can change the pandas version before we do.

https://github.com/NOAA-OWP/ngen-cal/issues/57

**Comment by robertbartel** [comment]
> The ngen-cal package has `pandas~=1.1.2` in the `setup.cfg` so I'm not sure how that would relate to seeing `1.1.5` here.

Given the added DMOD dependency on _ngen-cal_ in the branch for #394, the compatible release clause (I had to [look it up ](https://peps.python.org/pep-0440/#version-specifiers)to remember what to call it) for the _pandas_ dependency of _ngen-cal_ does explain why  version `1.1.5` was being installed.

**Comment by hellkite500** [comment]
Makes sense. We can likely migrate calibration to 2.0 if needed. Will have to do some testing though.
