### ISSUE TITLE
Complete implementations of Request Client functions

### ISSUE THREAD

**Issue by robertbartel** [NOAA-OWP/DMOD#431]
Add implementations of several CLI-accessible functions in _request_client.py_ within the _dmod.client_ package, which currently all raise `NotImplementedError`.   See [comments like this one](https://github.com/NOAA-OWP/DMOD/pull/424#discussion_r1325045030) in #424.

**Comment by aaraney** [comment]
And [this one](https://github.com/NOAA-OWP/DMOD/pull/424#discussion_r1325045106).
