### ISSUE TITLE
Add Python version matrix in Actions workflow to test with different versions of Python

### ISSUE THREAD

**Issue by robertbartel** [NOAA-OWP/DMOD#457]
Use a matrix with current Github Actions for automated Python tests to support testing with multiple (and hopefully all) supported versions of Python.  An example of this is set up in the [ngen-cal package's Action workflow config](https://github.com/NOAA-OWP/ngen-cal/blob/8d46c053b4a6d553d0b6e2c4ac539b5c092a2a63/.github/workflows/ngen-cal.yaml).

**Comment by aaraney** [comment]
This seems like a pretty easy issue that I can resolve today around lunch.
