### ISSUE TITLE
Worker image not building when Docker host is ARM

### ISSUE THREAD

**Issue by robertbartel** [NOAA-OWP/DMOD#475]
Encountered by @aaraney trying to build image on an ARM system.  Note that he used the revision in commit `9e8329fb605ea9eb3543c514e2cde2b144c9198f`, found in the `f/ngen_image_troute_build_fix/main` branch of my fork.

```
#0 40.51   Installing build dependencies: started
#0 42.94   Installing build dependencies: finished with status 'done'
#0 42.94   Getting requirements to build wheel: started
#0 43.04   Getting requirements to build wheel: finished with status 'error'
#0 43.04   error: subprocess-exited-with-error
#0 43.04
#0 43.04   × Getting requirements to build wheel did not run successfully.
#0 43.04   │ exit code: 1
#0 43.04   ╰─> [3 lines of output]
#0 43.04       <string>:86: DeprecationWarning: The 'warn' function is deprecated, use 'warning' instead
#0 43.04       WARNING:root:Failed to get options via gdal-config: [Errno 2] No such file or directory: 'gdal-config'
#0 43.04       CRITICAL:root:A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.
#0 43.04       [end of output]
#0 43.04
#0 43.04   note: This error originates from a subprocess, and is likely not a problem with pip.
#0 43.04 error: subprocess-exited-with-error
#0 43.04
#0 43.04 × Getting requirements to build wheel did not run successfully.
#0 43.04 │ exit code: 1
#0 43.04 ╰─> See above for output.
```

**Comment by hellkite500** [comment]
Looked through this briefly and I don't see gdal or gdal-dev in the rocky packages being installed. Might need to simply include those dependencies (see [here](https://github.com/CIROH-UA/NGIAB-CloudInfra/blob/dca9bbbbec4b7d9fe20b16afbf44311ca9eb2d70/docker/Dockerfile.ngen-deps#L26) for a docker build that has been tested cross platform.  I'm curious though how this was working at all (unless it was tested on some older t-route commits that managed to avoid any gdal dependencies???)

**Comment by aaraney** [comment]
Looks like [`fiona`](https://pypi.org/project/fiona/1.9.5/) is the culprit. `geopandas` depends on `fiona` and `fiona` by default will install from `pip` with a pre-built `libgdal`, _if it can_. It seems like the issue is `fiona` does not have a distribution with pre-build `libgdal` for the particular target.

> Fiona has several [extension modules](https://docs.python.org/3/extending/extending.html) which link against libgdal. This complicates installation. Binary distributions (wheels) containing libgdal and its own dependencies are available from the Python Package Index and can be installed using pip.

**Comment by aaraney** [comment]
@hellkite500's suggestion to install `gdal-devel` fixed the issue.
