### ISSUE TITLE
Address issues related to `DataTransmitMessage`'s `data` field type and handling of binary data

### ISSUE THREAD

**Issue by aaraney** [NOAA-OWP/DMOD#486]
The original title for this issue was _Change `DataTransmitMessage`'s `data` field type to accommodate binary data_.  See discussion [here](https://github.com/NOAA-OWP/DMOD/pull/424/files#r1326364510) and [here](https://github.com/NOAA-OWP/DMOD/pull/424/files#r1326358939).

It relates to #424 and may still have implications on #432.

However, as noted below, we cannot simply change the `data` field from `str` to `bytes`, as this breaks the implementation for serialization.  That said, this leaves in question whether/how we can support anything beyond unicode data.  This issue should track further discussion and work on addressing this.

**Comment by robertbartel** [comment]
As noted over in the issue, this looks like this would break JSON serialization for _ DataTransmitMessage_.

**Comment by aaraney** [comment]
Yeah you are right, @robertbartel. I was not using all of my brain when I was writing this up 😅. There does seem to be a larger issue that we cannot upload binary data without first encoding it in something like base64 or base85, but we should address that in a separate issue.
