### ISSUE TITLE
`SchedulerClient` tests failing after introducing #424

### ISSUE THREAD

**Issue by aaraney** [NOAA-OWP/DMOD#489]
After merging #424, it looks like the following [tests are now failing](https://github.com/NOAA-OWP/DMOD/actions/runs/7645554435/job/20832633763):

```python
test_async_make_request_1_a
test_async_make_request_1_b
test_async_make_request_1_c
test_async_make_request_2_a
test_async_make_request_2_b
test_async_make_request_2_c
test_async_make_request_3_a
test_async_make_request_3_b
test_async_make_request_3_c
```

The 1 tests are failing because [this](https://github.com/NOAA-OWP/DMOD/blame/406a9e592456d0974815a5544f8c0b48b37fe04e/python/lib/communication/dmod/communication/client.py#L619-L622) was added:

2 are failing because of [this](https://github.com/NOAA-OWP/DMOD/blame/406a9e592456d0974815a5544f8c0b48b37fe04e/python/lib/communication/dmod/communication/client.py#L572). 

3 are failing because of [this](https://github.com/NOAA-OWP/DMOD/blame/406a9e592456d0974815a5544f8c0b48b37fe04e/python/lib/communication/dmod/communication/client.py#L586). 

@robertbartel, can you confirm if the tests _should_ still be passing or has the implementation changed such that the failures should be what we are testing for? Im happy to fix this stuff, just not sure what the intended behavior is.

**Comment by robertbartel** [comment]
Yeah, I'd noticed and started looking at these a little bit ago.  So far, the failing tests that I've looked at closely have done so because there are now invalid, due to changed behavior.   I'm in the middle of fixing now.  There's a couple still I haven't confirmed yet, but I suspect it's the same.
