### ISSUE TITLE
client lib request_client has async co-routine calls not `await`ed

### ISSUE THREAD

**Issue by hellkite500** [NOAA-OWP/DMOD#549]
The following two calls to `_request_prep` should be `await`ed.

https://github.com/NOAA-OWP/DMOD/blob/98f8318809a68ba35e30c14a395586421672f09f/python/lib/client/dmod/client/request_clients.py#L344

https://github.com/NOAA-OWP/DMOD/blob/549aa4643fac4f36d4ea2f2efb29afd983195191/python/lib/client/dmod/client/request_clients.py#L378

**Comment by aaraney** [comment]
Thanks for reporting this, @hellkite500! Just opened #552 to fix this.
