### ISSUE TITLE
Unused parameter in function causing calls to fail which don't provide it

### ISSUE THREAD

**Issue by hellkite500** [NOAA-OWP/DMOD#550]
The function [_handle_data_upload](https://github.com/NOAA-OWP/DMOD/blob/98f8318809a68ba35e30c14a395586421672f09f/python/lib/externalrequests/dmod/externalrequests/maas_request_handlers.py#L296C105-L296C122) takes a `service_websocket` poitional parameter which isn't actually used in the function.

Calling from [handle_request](https://github.com/NOAA-OWP/DMOD/blob/98f8318809a68ba35e30c14a395586421672f09f/python/lib/externalrequests/dmod/externalrequests/maas_request_handlers.py#L330) doesn't provide an argument for this parameter, which lead to an error.

**Comment by aaraney** [comment]
Thanks for reporting this, @hellkite500! Just opened #551 to fix this.
