### ISSUE TITLE
Create NOTICE file and place dependency details and licenses here

### ISSUE THREAD

**Issue by robertbartel** [NOAA-OWP/DMOD#559]

**Comment by christophertubbs** [comment]
From #534:

> I suggest we add a NOTICE file in the root directory for the repo and start to put dependency license details here. I went ahead and created https://github.com/NOAA-OWP/DMOD/issues/559 for that, though feel free to either object or suggest alternatives if you have a better idea.

**Comment by aaraney** [comment]
related to #476. I believe this information is captured in a software bill of materials (SBOM).
