### ISSUE TITLE
Services broken due to Docker SDK and requests package issue

### ISSUE THREAD

**Issue by robertbartel** [NOAA-OWP/DMOD#628]
[This issue](https://github.com/docker/docker-py/issues/3256) with the Docker Python SDK is currently breaking DMOD services.  We are exploring potential workarounds

**Comment by aaraney** [comment]
Related https://github.com/psf/requests/issues/6707

**Comment by robertbartel** [comment]
Addressed by #629.  That pins to older versions of dependencies, so it isn't a permanent fix.  Once #629 is done, we should probably keep this open, lower the priority, and consider it blocked by the upstream Docker/requests issues.
