### ISSUE TITLE
DMOD image build failures due to t-route

### ISSUE THREAD

**Issue by robertbartel** [NOAA-OWP/DMOD#673]
Currently it is not possible to build the DMOD ngen worker image.  One of two different failures will occur, depending on whether the environment configuration is set to build the image with or without t-route.

*UPDATE*: the second failure has now been moved to its own issue: #676.

With t-route included by the image (which is the default), the following error is seen in the `rocky_build_troute` image build stage:

```bash
...
70.99 removing build/bdist.linux-x86_64/wheel
71.01 Successfully built troute_config-0.0.3.tar.gz and troute.config-0.0.3-py3-none-any.whl
71.04 python3: can't open file '/ngen/t-route/src/troute-nwm/setup.py': [Errno 2] No such file or directory
------
failed to solve: process "/bin/sh -c if [ \"${NGEN_WITH_ROUTING}\" == \"ON\" ]; then       export FC=gfortran ;       export F90=gfortran ;       mkdir ${WORKDIR}/t-route/wheels       && cd ${WORKDIR}/t-route       && ./compiler.sh       && cd ${WORKDIR}/t-route/src/troute-network       && python3 setup.py --use-cython bdist_wheel       && cp dist/*.whl ${WORKDIR}/t-route/wheels/       && cd ${WORKDIR}/t-route/src/troute-routing       && python3 setup.py --use-cython bdist_wheel       && cp dist/*.whl ${WORKDIR}/t-route/wheels/       && cd ${WORKDIR}/t-route/src/troute-config       && python3 -m build .       && cp dist/*.whl ${WORKDIR}/t-route/wheels/       && cd ${WORKDIR}/t-route/src/troute-nwm       && python3 setup.py bdist_wheel       && cp dist/*.whl ${WORKDIR}/t-route/wheels/ ;     fi" did not complete successfully: exit code: 2
Error: requested 'build' action failed (17); exiting without proceeding further
```

This is likely due to recent changes in t-route, though confirmation is still needed.

**Comment by robertbartel** [comment]
@aaraney, I don't suppose you can tell quickly from this exactly what needs to be adjusted in the image's t-route build stage, can you?

**Comment by aaraney** [comment]
Yep, [this line](https://github.com/NOAA-OWP/DMOD/blob/400ad4832ee82c325ad06dcffb6cbb3c0e6ca29f/docker/main/ngen/Dockerfile#L510) is the issue. I simplified some of the build process for `t-route` in https://github.com/NOAA-OWP/t-route/pull/784. As a result, `troute.nwm` no longer has a `setup.py`.

**Comment by aaraney** [comment]
So instead we can just build with:

```dockerfile
      && cd ${WORKDIR}/t-route/src/troute-nwm \
      && python3 -m build . \
      && cp dist/*.whl ${WORKDIR}/t-route/wheels/ ; \
    fi
```

**Comment by aaraney** [comment]
@robertbartel, just opened https://github.com/NOAA-OWP/DMOD/pull/674. That should fix it. The easiest way to test that locally might be to just pull down the patch file. I learned recently that you can download a patch from github by just tacking on `.patch` to the end of a PR url. So, https://github.com/NOAA-OWP/DMOD/pull/674.patch for example. I thought it was kind of neat at least.
