### ISSUE TITLE
Update example env to contain all relevant python package names

### ISSUE THREAD

**Issue by hellkite500** [NOAA-OWP/DMOD#8]
https://github.com/NOAA-OWP/DMOD/blob/ae5cae170d5b3afcc376354a5bfb9026ee324027/example.env#L38

Currently missing in env but used in main/nwm docker builds
PYTHON_PACKAGE_DIST_NAME_ACCESS
PYTHON_PACKAGE_DIST_NAME_EXTERNAL_REQUESTS

**Comment by aaraney** [comment]
Not sure exactly when this was fixed, but it is no longer an issue.
