### ISSUE TITLE
Error installing - update_package.sh run twice 

### ISSUE THREAD

**Issue by lcunha0118** [NOAA-OWP/DMOD#95]
In https://github.com/NOAA-OWP/DMOD/blob/master/doc/SUBSETTING_CLI_TOOL.md

In documentation, running same script twice. Is that correct?  
./scripts/update_package.sh python/lib/modeldata
./scripts/update_package.sh python/services/subsetservice

I also get a warning and an error when following documentation:
WARNING: Skipping dmod-subsetservice as it is not installed
ERROR: Could not find a version that satisfies the requirement dmod-modeldata>=0.3.0 (from dmod-subsetservice) (from versions: none)
ERROR: No matching distribution found for dmod-modeldata>=0.3.0

## Steps to replicate behavior (include URLs)

git clone git@github.com:NOAA-OWP/DMOD.git
cd <dmod_project_dir>       # replace with appropriate local directory
python -m venv venv         # or 'python3' if appropriate
source venv/bin/activate    # enter the venv in this terminal
pip install --upgrade pip
pip install -r requirements.txt
./scripts/update_package.sh python/lib/modeldata
./scripts/update_package.sh python/services/subsetservice
deactivate                  # exit the venv in this terminal

**Comment by robertbartel** [comment]
@lcunha0118 sorry this reply is coming so late.

The script should be run multiple times.  In short, it's installing (into the Python environment) several separate Python packages.  I can provide further detail on exactly what's going on if it would be helpful.

That said, there is a problem that I can reproduce when I use a fresh Python environment.  There is actually a third package that is needed  (`python/lib/communication`).  I will adjust the document and submit a PR.
